# Generated by Django 5.2.6 on 2025-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('alert_threshold', models.FloatField(default=5.0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('channel_name', models.CharField(max_length=200)),
                ('final_score', models.FloatField()),
                ('harmful_score', models.FloatField()),
                ('reliability_score', models.FloatField()),
                ('explanation', models.JSONField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=1)),
            ],
        ),
    ]
